### ISSUE TITLE
MappedRange does not implement expected equality semantics

### ISSUE THREAD

**Issue by itamarst** [mlenzen/collections-extended#169]
```python
>>> from collections_extended import MappedRange
>>> MappedRange(0, 100, True) == MappedRange(0, 100, True)
False
```

I would expect that if values are equal, the two `MappedRange` would be equal.

**Comment by mlenzen** [comment]
Yup, that seems perfectly reasonable. There is no existing equality implementation that is broken, so it should be a quick fix to add, I can't see any complicating factors.

**Comment by mlenzen** [comment]
Version 2.0.1 was just published to PyPI.

**Comment by itamarst** [comment]
Thank you!
