### ISSUE TITLE
bags comparisons should return NotImplemented

### ISSUE THREAD

**Issue by mlenzen** [mlenzen/collections-extended#34]

**Comment by mlenzen** [comment]
This can be a problem for testing as python2.7 (& pypy) have different behavior and actually do a comparison for different types.

**Comment by maweki** [comment]
Can you explain why exactly this should return NotImplemented?

**Comment by mlenzen** [comment]
@maweki Returning NotImplemented would allow another class to implement the comparison if it chose.

**Comment by maweki** [comment]
@mlenzen but they are implementing Set and the documentation states https://docs.python.org/3/library/collections.abc.html (at the end)

"Notes on using Set and MutableSet as a mixin:
2. To override the comparisons (presumably for speed, **as the semantics are fixed**), redefine __le__() and __ge__(), then the other operations will automatically follow suit."

So as I see it, for any class that implements Set, the operators <= and >= should have the same semantics as subset/superset.

**Comment by mlenzen** [comment]
@maweki That's a good point. I put the issue in because currently a TypeError is raised if the other object is not a bag. Returning NotImplemented seemed a better than that but proper sub/super set testing should be implemented for all types.

**Comment by mlenzen** [comment]
Bag comparison is now implemented for Sets. NotImplemented is returned in Python 3, a TypeError is raised in Python 2.
