### ISSUE TITLE
bidict

### ISSUE THREAD

**Issue by jab** [mlenzen/collections-extended#42]
Hi @mlenzen, I am the author of [bidict](https://bidict.readthedocs.org), a Python library that focuses on bidirectional maps. I just came across your library's `bijection`, and was wondering if you already knew about `bidict` when you wrote `bijection`, and either way, what you think of it. (Also, fun to see how similarly the .inverse property is implemented under the hood.) Just wanted to invite you to join forces if you're interested, as we're covering some overlapping ground. Best wishes!

**Comment by mlenzen** [comment]
Hey @jab, I hadn't seen bidict until just now. bijection is just a bit of code I had found myself copying between a few projects.  You have definitely fleshed out the idea out more than I did, I'll see if there's anything I can add.

As for this project, maybe I'll depend on bidict and have bijection just be a wrapper around it to maintain the api for a bit.

**Comment by jab** [comment]
Sounds great @mlenzen, look forward to hearing how it goes and improving things however I can!

**Comment by jab** [comment]
Hey @mlenzen, came out with a new and much improved version of bidict last month (0.12.0) and wanted to let you know in case of interest.

(((
The two most significant improvements are (1) bulk updates fail clean (so if an update causes a `ValueDuplicationError` for example, you can be sure that none of the given items was inserted), and (2) you can now specify custom on-key-duplication and on-value-duplication behaviors (RAISE, OVERWRITE, IGNORE) when updating a bidict.
More info in [the changelog](https://bidict.readthedocs.io/en/v0.12.0/changelog.html).
)))

**Comment by mlenzen** [comment]
Closing this as there isn't anything really actionable.

**Comment by jab** [comment]
Might you still be interested in depending on (and wrapping) bidict, as you proposed upthread? Would be happy to consider any changes to bidict that could make that easier, in the interest of eventually converging on a single, convergent base implementation where the community could pool resources.
