### ISSUE TITLE
RangeMap: No way to get end of highest range?

### ISSUE THREAD

**Issue by MareinK** [mlenzen/collections-extended#84]
I couldn't find any way to get the end of the highest range from a RangeMap. For example:

```
rm = RangeMap()
rm[5:10] = 'test'
print(max(rm))  # output: 5
```

I would expect `10`, or expect some other way of getting this.

I've created #85 as a possibility to address this.

**Comment by mlenzen** [comment]
Just merged in the changes to add start and end.
